package com.imdmanuel.book_library.enums;

public enum NotificationType {
    LOAN_CONFIRMATION,
    LOAN_DUE_REMINDER,
    LOAN_OVERDUE,
    LOAN_RETURN_CONFIRMATION,
    RESERVATION_CONFIRMATION,
    RESERVATION_AVAILABLE,
    RESERVATION_EXPIRED,
    RESERVATION_CANCELLED,
    PENALTY_APPLIED,
    SUSPENSION_WARNING,
    SUSPENSION_NOTICE,
    ACCOUNT_CREATED
}
